name: Clang Format Lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './src'
          extensions: 'h,cpp'
          clangFormatVersion: 17